export let lang;
export let langIndex = "ko";

fetch("../lang.json").then((response) => response.json()).then((json) => lang = json);

document.getElementById("lang-select").addEventListener("change", (e) => {
	langIndex = e.target.value;
	document.querySelector(".title-bar-text").innerText = lang[langIndex].title;
	document.querySelector("#logout-btn").innerHTML = lang[langIndex].logout;
	document.querySelector("#sign-in-id-label").innerHTML = lang[langIndex].id;
	document.querySelector("#sign-in-pw-label").innerHTML = lang[langIndex].pw;
	document.querySelector("#sign-in-btn").innerHTML = lang[langIndex].signin;
	document.querySelector("#sign-in-42-btn").innerHTML = lang[langIndex].signin42;
	document.querySelector("#sign-up-btn").innerHTML = lang[langIndex].signup;
	document.querySelector("#sign-up-id-label").innerHTML = lang[langIndex].id;
	document.querySelector("#sign-up-pw-label").innerHTML = lang[langIndex].pw;
	document.querySelector("#sign-up-check-pw-label").innerHTML = lang[langIndex].checkPw;
	document.querySelector("#sign-up-email-label").innerHTML = lang[langIndex].email;
	document.querySelector("#sign-up-email-btn").innerHTML = lang[langIndex].authEmail;
	document.querySelector("#email-info").innerText = lang[langIndex].emailInfo;
	document.querySelector("#sign-up-code-label").innerHTML = lang[langIndex].emailCode;
	document.querySelector("#sign-up-code-btn").innerHTML = lang[langIndex].checkEmail;
	document.querySelector("#sign-up-cancel").innerHTML = lang[langIndex].goBack;
	document.querySelector("#sign-up-submit").innerHTML = lang[langIndex].ok;
	document.querySelector("#l-tab a").innerText = lang[langIndex].offline;
	document.querySelector("#t-tab a").innerText = lang[langIndex].tournament;
	document.querySelector("#m-tab a").innerText = lang[langIndex].online;
	document.querySelector("#l-set").innerText = lang[langIndex].lSet;
	document.querySelector("#name1").innerText = `1${lang[langIndex].playerName}`;
	document.querySelector("#name2").innerText = `2${lang[langIndex].playerName}`;
	document.querySelector("#l-gp-label").innerText = lang[langIndex].gamePoint;
	document.querySelector("#l-ok").innerText = lang[langIndex].ok;
	document.querySelector("#t-set").innerText = lang[langIndex].tSet;
	document.querySelector("#t-gp-label").innerText = lang[langIndex].gamePoint;
	document.querySelector("#num-people").innerText = lang[langIndex].nPeople;
	document.querySelector("#index-0").innerText = lang[langIndex].select;
	document.querySelector("#make-room").innerText = lang[langIndex].roomMake;
	document.querySelector("#r-set-win").innerText = lang[langIndex].roomSet;
	document.querySelector("#m-set").innerText = lang[langIndex].mSet;
	document.querySelector("#rn-label").innerText = lang[langIndex].roomName;
	document.querySelector("#m-gp-label").innerText = lang[langIndex].gamePoint;
	document.querySelector("#m-pw-label").innerText = lang[langIndex].password;
	document.querySelector("#m-ok").innerText = lang[langIndex].ok;
	document.querySelector("#cancel").innerText = lang[langIndex].cancel;
	document.querySelector("#show-gp").innerText = `${lang[langIndex].gamePoint}: `;
});