export let lang;
export let langIndex = "ko";

fetch("../lang.json").then((response) => response.json()).then((json) => lang = json);

document.getElementById("lang-select").addEventListener("change", (e) => {
	langIndex = e.target.value;
	document.querySelector(".title-bar-text").innerText = lang[langIndex].title;
	document.querySelector("#logout-btn").innerHTML = lang[langIndex].logout;
	document.querySelector("#sign-in-id-label").innerHTML = lang[langIndex].id;
	document.querySelector("#sign-in-password-label").innerHTML = lang[langIndex].password;
	document.querySelector("#sign-in-2factor").innerHTML = lang[langIndex].varify;
	document.querySelector("#sign-in-code-label").innerText = lang[langIndex].code;
	document.querySelector("#sign-in-btn").innerHTML = lang[langIndex].signin;
	document.querySelector("#sign-in-42-btn").innerHTML = lang[langIndex].signin42;
	document.querySelector("#sign-up-btn").innerHTML = lang[langIndex].signup;
	document.querySelector("#sign-up-id-label").innerHTML = lang[langIndex].id;
	document.querySelector("#sign-up-password-label").innerHTML = lang[langIndex].password;
	document.querySelector("#sign-up-check-password-label").innerHTML = lang[langIndex].checkPassword;
	document.querySelector("#sign-up-email-label").innerHTML = lang[langIndex].email;
	document.querySelector("#sign-up-email-btn").innerHTML = lang[langIndex].varify;
	document.querySelector("#email-info").innerText = lang[langIndex].emailInfo;
	document.querySelector("#sign-up-code-label").innerHTML = lang[langIndex].code;
	document.querySelector("#sign-up-code-btn").innerHTML = lang[langIndex].checkEmail;
	document.querySelector("#sign-up-cancel").innerHTML = lang[langIndex].goBack;
	document.querySelector("#sign-up-submit").innerHTML = lang[langIndex].submit;
	document.querySelector("#offline-tab a").innerText = lang[langIndex].offline;
	document.querySelector("#tournament-tab a").innerText = lang[langIndex].tournament;
	document.querySelector("#online-tab a").innerText = lang[langIndex].online;
	document.querySelector("#offline-info").innerText = lang[langIndex].lSet;
	document.querySelector("#name-input1-label").innerText = `1${lang[langIndex].playerName}`;
	document.querySelector("#name-input2-label").innerText = `2${lang[langIndex].playerName}`;
	document.querySelector("#offline-game-point-label").innerText = lang[langIndex].gamePoint;
	document.querySelector("#offline-submit").innerText = lang[langIndex].submit;
	document.querySelector("#tournament-info").innerText = lang[langIndex].tSet;
	document.querySelector("#tournament-game-point-label").innerText = lang[langIndex].gamePoint;
	document.querySelector("#num-people").innerText = lang[langIndex].nPeople;
	document.querySelector("#index-0").innerText = lang[langIndex].select;
	document.querySelector("#make-room-btn").innerText = lang[langIndex].roomMake;
	document.querySelector("#online-info").innerText = lang[langIndex].mSet;
	document.querySelector("#online-room-name-label").innerText = lang[langIndex].roomName;
	document.querySelector("#online-game-point-label").innerText = lang[langIndex].gamePoint;
	document.querySelector("#online-password-label").innerText = lang[langIndex].password;
	document.querySelector("#online-room-submit").innerText = lang[langIndex].submit;
	document.querySelector("#online-room-cancel").innerText = lang[langIndex].cancel;
	document.querySelector("#show-game-point").innerText = `${lang[langIndex].gamePoint}: `;
});